apiVersion: v1
kind: Service
metadata:
    name: node-service
spec:
    type: NodePort
    ports:
        - targetPort: 8000
          port: 80
          nodePort: 30001
    selector:
        release: beta
        type: poc