apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    release: beta
    type: poc
  name: deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      type: poc
  template: 
    metadata: 
      labels: 
        release: beta
        type: poc
      name: node-pod
    spec: 
      containers: 
        - image: "GusLuck/nodejs-hello-word/node:1.1"
          name: node-container
          ports: 
            - containerPort: 8000
